# Site settings
title:       CS-JEDI
author:      a
baseurl:     "/~15996"
url:         "https://cs.cmu.edu"
header_pages:
  - pedag_found.md
  - library.md 
  - public_materials.md
  - faqs.md
keywords: []

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough']
permalink:    pretty
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME

blank-link: ""


canvas-link: "https://canvas.cmu.edu/courses/32467"
syllabus-link: "https://docs.google.com/document/d/1t8mzATCcLJ7ZcsldR7EE8XSfHzrBHnwNU53XNuKKnN8/edit?usp=share_link"
anonymous-feedback-link: "https://docs.google.com/forms/d/e/1FAIpQLScaQoWpn7uiZFVG6QKpuLHGAJuzbmCALQ6bAr9dYQOjq_KMig/viewform?usp=sf_link" 
google-drive-link: "https://drive.google.com/drive/folders/1QYOYXQcK4a8fbPjIUV-eps4T-qnlm53Q?usp=share_link"
discussion-guide-link: "https://docs.google.com/document/d/1h4itwjJdh60AhIlLs8B6jTPpopofYFFeHvGl-hrfchE/edit?usp=share_link"
groups-and-lenses-link: "https://docs.google.com/spreadsheets/d/1xzeipTV3tVij9JchFGIm5MOSKmX6T9BxfJ8yaoeuK2s/edit?usp=share_link"
project-overview-link: "https://docs.google.com/document/d/1-0qZU_iC6ME4d7J7pptsjcKBh9aF8GQWL6wcQ2XtqsA/edit?usp=share_link"
glossary-link: "https://docs.google.com/document/d/1-0qZU_iC6ME4d7J7pptsjcKBh9aF8GQWL6wcQ2XtqsA/edit?usp=share_link"
library-link: "https://docs.google.com/spreadsheets/d/1fIZ_Jk95J4ZjMw37tsLmqemLTUplo3BzfVrmmqMDM4A/edit?usp=share_link"
schedules-link: "https://docs.google.com/document/d/1ZHxUqOtY37Tjr-bD_AQYEadfqLH0p1d0fGG5v_Ap3XE/edit?usp=share_link"
make-up-link: "https://docs.google.com/document/d/1oJZxt2oVtr9sXNOG9KipdByRIU6sKAvtFogr2SzyGq0/edit?usp=share_link"
supportive-resources-link: "https://docs.google.com/document/d/1tCHISoy70v_wNV1M2E7Pyd4ubLAoJVO1teP89wpckn8/edit?usp=share_link"
get-involved-link: "https://docs.google.com/document/d/19qzDTZZUV9g1b8W-XC95jIhamaGpJUuD22a78QM0Q5c/edit?usp=share_link"

pre-class-1-link: "https://docs.google.com/document/d/16L9_vK0Lhhr-3k4PWmUoUaOEZyMX3_wnzXqJOCMWtx0/edit?usp=share_link"
pre-class-2-link: "https://docs.google.com/document/d/1WyF-gQ930I3auaPN-sWKgZQzbqHagVUj_LBthXwP5yY/edit?usp=share_link"
pre-class-3-link: "https://docs.google.com/document/d/1ZNY-uU-T7ELo9z9YO2jLJ2rM1h8AyPM1S8O8rg6SSI8/edit?usp=share_link"
pre-class-4-link: "https://docs.google.com/document/d/1grPYUgnBlDdxUqwUki1ZtIJWFc36fqFFbWJ7i_TGeGU/edit?usp=share_link"
pre-class-5-link: "https://docs.google.com/document/d/18MqEJTGVRmIFbpqH22GsH98OTeCZ_Hn1FtvlWmgDQgw/edit?usp=share_link"
pre-class-6-link: "https://docs.google.com/document/d/1iaw9vrFHmFc7HjWj7GFnYINuZUzW13lH6cuIrRUz8tQ/edit?usp=share_link"
post-class-link: "https://docs.google.com/document/d/1u_qdAcvQMGGIz3HtgrPw9dET78If82TsPp0oBolodm8/edit?usp=share_link"


lec-slides-1-link: ""
lec-slides-2-link: ""
lec-slides-3-link: ""
lec-slides-4-link: ""
lec-slides-5-link: ""
lec-slides-6-link: ""

