# Site settings
title:       CS-JEDI
author:      a
baseurl:     "/~15996"
url:         "https://cs.cmu.edu"
header_pages:
  - spring2022.md
  - about.md
  - faqs.md
  - archive.md
keywords: []

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'strikethrough']
permalink:    pretty
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - CNAME
